### ISSUE TITLE
Inspector List Due 7/18/19

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#100]
Provide updated inspector prioritization list to ROW. 
Due 7/18/19 by noon.

**Comment by TracyLinder** [comment]
@johnclary the csv files are [here](https://teams.microsoft.com/_#/tab::7dc26d1f-21aa-43dd-9dd9-ab25188b15a7/General?groupId=02b31ca7-6853-4783-bdbb-81bf6f5fc459&threadId=19:6125816a2bd34142a9b23fc916a968b8@thread.skype&ctx=channel&context=Projects%252FInspector%2520Dashboard).

**Comment by johnclary** [comment]
@TracyLinder processed data attached here: 
[https://app.zenhub.com/files/183466621/35355e70-af2a-4c22-bfe0-4bd572da4767/download](https://app.zenhub.com/files/183466621/35355e70-af2a-4c22-bfe0-4bd572da4767/download)

**Comment by TracyLinder** [comment]
[July 18 2019 Inspection List](https://github.com/cityofaustin/atd-amanda/files/3408046/July.18.2019.xlsx)
