### ISSUE TITLE
Meeting: Inspector Prioritization Ph 2 (Technical)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#113]
**Meeting Date:** Friday Aug 9 @ 2:30pm

**Attendees:** John Clary, Tracy Linder

**Objective:** Discuss moving forward with Phase 2 of this project. 

**Agenda:**

- [ ] Review notes from the Ph 1 Review, #83 
- [ ] Review Ph 2 goals, [here](https://teams.microsoft.com/_#/xlsx/viewer/customspo/https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FATD~2FDTS~2FShared%20Documents~2FProjects~2FInspector%20Dashboard~2Finspector_priority_workbook.xlsx?threadId=19:6125816a2bd34142a9b23fc916a968b8@thread.skype&baseUrl=https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FATD~2FDTS&fileId=01011006-4C26-4217-A6D5-66EE3BA188B1&ctx=custom-spo&viewerAction=view) 

- [x] Next steps

**Comment by johnclary** [comment]
@TracyLinder I'd like to consider Phase 2 blocked until we develop the public ROW datasets and automate the Phase 1 version of this. Can we repurpose this discussion to focus on [#89](https://app.zenhub.com/workspace/o/cityofaustin/atd-amanda/issues/89)?

**Comment by TracyLinder** [comment]
**Meeting Notes**

- T - Ask Julia for the squl query for [Issued Construction Permits](https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu/data)
- ? - How to handle permit segments. It would be nice to have them comma separated in a column. (Tracy needs to learn how to do that.)
- Don't want to move forward w/ phase 2 until we get ph 1 automated.

 **Next Steps**

1. Define data
2. Take that to AMANDA CTM - figure out db account.
    *John talked to Stacey, maybe somebody talked to Chad (DBA), Gita, maybe Dartez

**Comment by TracyLinder** [comment]
Email sent to Julia this afternoon regarding the query she's using.
