### ISSUE TITLE
Meeting: UC Self-Assignment Demo & Testing

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#117]
**Date/Time:** 8/16/19 @ 2:30pm

**Attendees:** Tracy Linder, Isaiah Lewallen, Jaclyn Lozano, Greg Pepper

**Objective:** Demo the UC Self-Assignment features, and discuss UAT.

**Comment by amenity** [comment]
@TracyLinder - It looks like this took place in Sprint 5, so sticking that milestone on it. Anything else needed before it's closed?
