### ISSUE TITLE
ATD Backlog Cleanup 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#12]
Clean up the backlog. 
Group like items together, and arrange them into logical sprint groups.

**Comment by TracyLinder** [comment]
Here's the backlog. 
[This](https://cityofaustin.sharepoint.com/sites/CTM/TEAMSITES/ECMIM/AMANDA/Lists/AMANDA%20Governance%20BNS%20List/DispForm.aspx?ID=61&Source=https%3A%2F%2Fcityofaustin%2Esharepoint%2Ecom%2Fsites%2FCTM%2FTEAMSITES%2FECMIM%2FAMANDA%2FLists%2FAMANDA%2520Governance%2520BNS%2520List%2FBNS%2520by%2520Department%2Easpx&ContentTypeId=0x010007ACA67C3FD7FA4BBA28A919EA1D309F) needs to be included also. 
[ROW Backlog Development Estimate.xlsx](https://github.com/cityofaustin/atd-amanda/files/3154623/ROW.Backlog.Development.Estimate.xlsx)

**Comment by johnclary** [comment]
Done. Closing.
