### ISSUE TITLE
Dev Huddle - DAPCZ Agenda Upgrade

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#146]
### Outcome:
**The Dev Huddle concluded that KNACK is the best solution for this project, and estimated the project to take 2 months.**

**Date:** 9/30/19 @ 10:30am
**Attendees**: Tracy Linder, Diana Martin, Surbhi Bakshi

**Agenda:**
• (Tracy) – Explain what DAPCZ is, and who the stakeholders are
• (Tracy) – Overview of the current DAPCZ Agenda process
• (Tracy) – Outline the requested DAPCZ Agenda future state
• (Devs) – Propose a solution
• (Devs) – Identify any knowledge gaps needed to provide a work estimate
• (Everyone) – Next Steps

**Comment by dianamartin** [comment]
### FIELDS TO INCLUDE
- Project Name
- Project Description
- Project Location
- Customer Name
- Customer Phone Number
- Customer Email
- Customer Company Name
- Start Date
- Duration
- Project Status
- TCP Reviewer
Comment
Month JULY
Month AUG
Month SEPT
Month OCT

**Comment by johnclary** [comment]
@TracyLinder do you have notes to add here?

**Comment by dianamartin** [comment]
I checked and had very minimal notes about this meeting. @SurbhiBakshi did you have notes on this? (on 9/30)

**Comment by amenity** [comment]
@TracyLinder - It looks like this took place in Sprint 8, so sticking that milestone on it. Anything else needed before it's closed?

**Comment by TracyLinder** [comment]
## Pics From Dev Huddle:
---

![DAP1](https://user-images.githubusercontent.com/49930868/67706749-51d00800-f987-11e9-8708-faafa14120ce.jpg)
![DAP2](https://user-images.githubusercontent.com/49930868/67706757-54326200-f987-11e9-9eb5-90ee453e937c.jpg)
![DAP3](https://user-images.githubusercontent.com/49930868/67706762-58f71600-f987-11e9-84de-6b98536a9ed9.jpg)
