### ISSUE TITLE
Report Requests: TCI Monthly Metrics

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#149]
## Monthly Traffic Control Inspection Metrics Report

**Purpose:** To aid in the monthly performance metrics provided to executive management 

**Primary User:** Executive Management

**User Search Parameters:**
* Start Date
* End Date
* Previous Month
* Month to Date

**Query Parameters:**
* All User Parameters
* TCI Fees
* TCI Attempt Results

**Report Data (Include for each Item that meets parameters):**
* Total amount of inspection fees invoiced for the month, grouped by the inspector who created the invoice
* Total amount of inspection reports created for the month, grouped by the inspector who created the report
    * Report count = count # of attempt results on TCI process

**Misc:**
* User does not need to see details for this information, just the totals
* Consider 1st grouping to be by the inspector, then provide the totals under his/her name

*Migrated to [atd-data-tech #1742](https://github.com/cityofaustin/atd-data-tech/issues/1742)*

**Comment by TracyLinder** [comment]
This request is the second part of issue #147

**Comment by TracyLinder** [comment]
* Synced w/ R. Ward about this request this morning. Notes clarifying the request have been added to the description. I'll also be creating a new ticket for the 2nd report request. 
* I told Ryan I can write the queries for these reports this week, and will submit a CTM ticket to have the AMANDA CTM team do the Crystal Report work. These reports need to be available to the user in the ATD custom report menu. 
* Ryan will provide me with the 5 or 6 inspection fees that are being used.

**Comment by johnclary** [comment]
@TracyLinder email Mooney about this.
