### ISSUE TITLE
Report Request:  Parking Benefit District

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#156]
Email From Paloma 9/27/19:

Hi Tracy,

Joseph, Van, and I are wondering if it’s possible to run an AMANDA report that captures the payments made for the following fees:
-	TURP Metered Parking Space (Note: The FDU is 5125 2400 9100 4062 but it is shared with other ROW fees)
-	Parking Space Permit Fee (Note: The FDU is 5125 2400 9100 4087 but this one is also shared with other ROW fees … I think)

The catches:
-	We would only need these fees for certain property IDs/street segments.  See the attached list.
-	The report would need to include:
o	The date/month the fee was paid
o	The property ID/street segment affiliated with the payment
o	The permit number affiliated with the payment
-	And ideally, the report would run monthly … probably sometime in the first week of the month to capture all fees paid in the previous month

Do you think this is doable?  If so, please let us know what time you would need to produce this report and any future time needed to run the report monthly.

In case you’re curious, we need this data in order to satisfy the requirements of the Parking Benefit District program.  This program requires that 51% of meter revenue be returned to the District.  This meter revenue would include permit/ROW usage fees collected.

**Comment by TracyLinder** [comment]
These are the segment IDs provided in Paloma's email.
[parking district segment ID's (002).xlsx](https://github.com/cityofaustin/atd-amanda/files/3806059/parking.district.segment.ID.s.002.xlsx)

**Comment by TracyLinder** [comment]
Email response:

Hi Everyone,

This request snuck right by me!

So I plugged those segments into an existing query and got the attached data. I’m not sure how to add the segment affiliated to the permit to this query, so I’ll need to do some research on that. 

On the spreadsheet attached there are some duplicate fees, for various reasons. For example, line 17 & 18 are the same fee; it was paid with 2 different checks and some of that check was applied to another fee as well. 

Can you please check out the attached data and give me some feedback? Other than the affiliated segment, does it meet your criteria? 

Thanks,

**Comment by TracyLinder** [comment]
[Parking Benefit Report.xlsx](https://github.com/cityofaustin/atd-amanda/files/3806152/Parking.Benefit.Report.xlsx)
This is the data sent in my response.

**Comment by johnclary** [comment]
@TracyLinder  next steps: reach out to CTM for help.

**Comment by TracyLinder** [comment]
The query is [here](https://github.com/cityofaustin/atd-amanda/blob/master/plsql-queries/PBD.sql)

**Comment by TracyLinder** [comment]
**Email to everyone on original request:**

[Data attached to email here](https://github.com/cityofaustin/atd-amanda/files/3991068/West.Campus.Data.xlsx)



Hi Everyone,

I’ve attached the data requested. I was unable to include the segment on each detailed fee line, so there are 2 sets of data. One gives you a total for each segment, and one gives you the fee detail you requested, without the segment info. (The totals match up, so you don’t have to check it unless you just really want to.)

Please let me know if there are any questions. Merry Christmas!

Tracy Linder
IT Business Systems Analyst Sr.
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
Final query used is [here](https://github.com/cityofaustin/atd-amanda/blob/master/plsql-queries/WestCampusParking.sql).
