### ISSUE TITLE
Meeting: Inspector Prioritization Project Sync

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#157]
## Meeting Info
**Participants:** Tracy, Ryan Mooney
**Date/Time/Location:** 11/12/19, 11:30am, Toomey @ Ryan's Office

## Objective & Agenda
Ryan has recently taken over the ROW inspections group. The purpose of this meeting is to review the project phases and scope, and realign the project if needed. 

* Review current report
    * Weekly due date - does it still work on Tuesdays? When will the inspectors review the report?
* Review Future Phases
    * Is anything missing?
    * Have priorities changed
* Ryan's KNACK Ideas
    * Discovery, scope
    * Where does this fit in w/ current phases?

**Comment by TracyLinder** [comment]
This needs to be rescheduled.

**Comment by johnclary** [comment]
Scheduled for 11/26 at 330pm.

**Comment by TracyLinder** [comment]
KNACK story: AS the TCI supervisor, I want the inspectors to be able to pull up their area list, same info & same sorting. They should have the ability to click 'done' on a row, and that row/inspection would remove itself from the list. 

Ability to pull another area as well, if needed for covering another area. 

As the TCI supervisor, I want to the ability to look at data, like how many rows were marked done on any given day.

**Comment by TracyLinder** [comment]
Ryan's Priority:
KNACK integration
Then the next phases

**Comment by TracyLinder** [comment]
More KNACK notes...

The inspection data would still need to be refresh each week. Ryan thinks we could delete all records that were not marked 'done'. We'll need to think of a way to identify which records are current & which are 'done' records (other than the status, or maybe status is good enough?).
