### ISSUE TITLE
Meeting: Post Payment Bug Fixes Work Session

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#164]
### Objective:
Discuss possible solutions for 2 bugs related to the post payment features:
- Folder ‘Issued By’ 
- EX – Work Date in the past issue (lets discuss updating the EX extension process as a possible fix)

**Date/Time/Location:** Nov 26, 2019 | 2-3pm | Toomey Rd Conf Room
**Attendees:** Tracy, Paloma, Kim, Izzy

**Comment by johnclary** [comment]
@TracyLinder add your notes.
