### ISSUE TITLE
UAT on Clickmap

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#166]
*Migrated to [atd-data-tech #1777](https://github.com/cityofaustin/atd-data-tech/issues/1777)*

**Comment by johnclary** [comment]
Tracy is doing this tomorrow I12/18)

**Comment by amenity** [comment]
@johnclary - do you happen to know the status of this?

**Comment by amenity** [comment]
- Permit needs to be automatically emailed to DSD in addition to applicant wants to be copied on all excavation permits (Paloma has discussed an alternate way of doing this with them, but tbd)
