### ISSUE TITLE
Create Email Template - LM Self Assignment 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#178]
An email is auto-generated when the LM child permit/folder is auto-created from the SP folder. The email informs the SP applicant of the LM review requirement, and should give them instructions for self-assigning & submitting an application. 

- [ ] LM team will draft the template
- [ ] LM team to email the template to Tracy
- [ ] Tracy perform review of the template
- [ ] Tracy to post the template on the Trello board for ROWMAN ph 3

*Migrated to [atd-data-tech #1517](https://github.com/cityofaustin/atd-data-tech/issues/1517)*

**Comment by TracyLinder** [comment]
[LM Current Email.pdf](https://github.com/cityofaustin/atd-amanda/files/3888714/LM.Current.Email.pdf)
This is the email template that is going out right now, and should be updated.

**Comment by johnclary** [comment]
Tracy followed-up up with Andy and Melissa today asking for new template.
