### ISSUE TITLE
Post Payment UAT

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#181]
Unisys asked me to do UAT on these post payment features: 

- Remove PP from commercial DS
- DS default status issue
- EX only on pvt
- EX charges on each permit when multiple streets

**Comment by johnclary** [comment]
Scheduled for tomorrow

**Comment by TracyLinder** [comment]
![image](https://user-images.githubusercontent.com/49930868/71634228-e8b37d80-2bdf-11ea-859b-dba1c53beb5e.png)
