### ISSUE TITLE
Mtg 12/12/10: SQL Review for PBD Report

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#183]
Hi Sergio,

Thanks for being open to helping me with the query for this request. The current query I’m using is linked in the issue’s comments.  

You’ll likely need a intro to the data for this to make any sense, but you did ask for the opportunity to do some homework, so I’ve done my best to give you a high level overview below. 

- I’ve been asked to provide AMANDA fee data for specific fees collected if that fee is associated with specific street segments.

    - The specific street segments were provided by the requestor, and are linked in the issue comments. 
    - The specific fees were provided by the requestor and are in the issue description. 
    - The street segments relate to parking benefit districts (PBD). ATD maintains a few PBD’s; the money we collect on parking is put into a fund that will only be used to improve that district. 
- Each AMANDA permit folder must have at least one street segment on the folder property table.
- Each row in the result set must include the associated PBD street segment. This will allow staff to sort/filter/group the fees by the PBD and transfer the correct amount of money into the fund. 
    - **This is the requirement that I need help with.** I don’t know how write “tell me which segment(s) in the where clause is associated with this fee” in sql. 

The query is pulling from a number of tables; the 2 most important are folderproperty and accountbillfee 
- Folderproperty: Data about the segments/properties of a permit folder
- Accountbillfee: Data about the fees billed and collected on a permit folder
![image](https://user-images.githubusercontent.com/49930868/70756003-fd97a200-1d00-11ea-9aea-d0c2bf6ff95d.png)

I’m looking forward to learning from you!

All the Best,
Tracy

**Comment by TracyLinder** [comment]
Tracy: Check query for duplicate segment id's

**Comment by sergiogcx** [comment]
Glad I could help, I moved this to review Q/A. Let know, if more more is needed.

**Comment by TracyLinder** [comment]
**PBD query after work sesh w/ Sergio on 12/16/19**

SELECT   fp.propertyrsn, SUM( abf.feeamount)

  FROM accountbillfee abf

   JOIN validaccountfee vaf ON (abf.feecode = vaf.feecode)

   JOIN folder f ON (abf.folderrsn = f.folderrsn)

   JOIN folderproperty fp ON (f.folderrsn = fp.folderrsn)

   JOIN accountbill ab ON (abf.billnumber = ab.billnumber)

   JOIN accountpaymentdetail apd ON (apd.billnumber = ab.billnumber)

   JOIN accountpayment ap ON (ap.paymentnumber = apd.paymentnumber)

  WHERE f.foldertype IN ('DS','EX','RW', 'SCP', 'ECV')

    AND fp.propertyrsn in (2019053,2019053,2019053,2019053,2019054,2019028,2019028,2019028,2019029,2019029,2019029,2019054,2018985,2019008,2019008,2019008,2018986,2018957,2018957,2018957,2018937,2018913,2018913,2018914,2019001,2019001,2019002,2018984,2019050,2019050,2019027,2019027,2019001,2018958,3190725,3190725,2019079,2019099,2019099,2019150,2019122,2019122,2019122,2019082,2019083,2019083,2019177,2019135,2019118,2019118,2019119,2019098,2019098,2019119,2019135,2041219,2041219,2019164,2019164,2043965,2019144,2019144,2019133,2019144,2019144,2019164,2019142,2019142,2019142,2019143,2019131,2019131,2019132,2019112,2019155,2019111,2019111,2019111,2019047,2019076,2019096,2017754,2017754,2017754,2017754,2017754,2017754,2017754,2017754,2017630,2017630,2017630,2017554,2017554,2017554,2017554,2017554,2017470,2017470,2017470,2017470,2017470,2017382,2017382,2017301,2017297,2017297,2017039,2017039,2017039,2017042,2017042,2017040,2017040,2017040,2017040,2017040,2017189,2017189,2017189,2017189,2017189,2017189,2017189,2019121,2019121,2019082,2019083,2019083,2019083,2019029,2019007,2019007,2019007,2019007,2019007,2019007,2019008,2018985,2018985,2018957,2018957,2018957,2018958,2018958,2018937,2018937,2018937,2018937,2018913,2018913,2018983,2019001,2019049,2019049,2019049,2019049,2019078,2019078,2019078,2019078,2019098,2019098,2019098,2019098,2019098,2019118,2019118,2019118,2019134,2019134,2019134,2019134,2041219,2019164,2019144,2019133,2019113,2019113,2019113,2019131,2019155,2019155,2019111,2017710,2017776,2017710,2017327,2017371,2017371,2017371,2017291,2017291,2017291,2017300,2017310,2017388,2017474,2017636,2017631,2017631,2017631,2017108,2017108,2017108,2017108,2017198,2017193,2017193,2017190,2017187,2017188,2017188,2017184,2017184,2017241,2017246,2017274,2017151,2017151,2017151,2017111,2017295,2017377,2017377,2017467,2017467,2017467,2017467,2017548,2017548,2017548,2017624,2017624,2017624,2017732,2017732,2017732,2017732,2017732,2017732,2017732,2017715,2017546,2017546,2017546,2017497,2017282,2017362,2017362,2017362,2017362,2017348,2017348,2017348,2017265,2017265,2017265,2017265,2017265,2017265,2017265,2017265,2017265,2017265,2019781,2019781,2019780,2019780,2019780,2017275,2017275,2017275,2017275,2017286,2017286,2017284,2017290,2017290,2017290,2017296,2017298,2017298,2017424,2017424,2017424,2017424,2017424,2017424,2017424,2017427,2017427,2017427,2017427,2017490,2017490,2017539,2017539,2017578,2017614,2017614,2017691,2017691,2017691,2017691,2017619,2017619,2017619,2017619,2017619,2017619,2017619,2017619,2017547,2017547,2017540,2017540,2017540,2017540,2017540,2017491,2017491,2017491,2017491,2017491,2017498,2017498,2017498,2017498,2017498,2017150,2017135,2017034,2017189,2017579,2017579,2017579,2017579,2019133,3254250,3254250,3311072,3311072,3311072,3311072,2019001,3554342,3692187,3692187,3692187,3311072,3311072,3311072,3348612,3692187,3311072,2017467,2017467,3692187,2018958,2019119,2018958,2019122,2019122,2019199,2019199,2017246,2017246,2017296,2017631,2017630,2017630,2017630,2019122,5062327,5062325,5062325,3554346,3554344,2017323,2017245,2019199,2019199,3348612,5062327,5135089,5135089,5135127,5062325,5135076,5135076,5135076,2017289,2017289,2017289,2017192,2017192,2017192,2017192,2017035,2017035,2017035,2017035,2017199,2017205,0,2017286,2017286,2017357,2017357,2017357,2019150,2017625,2017625,2017548,2017715,2017715,2021065,2021065,2021644,2021644,2020879,2038583,2038583,2020842,2020842,2020862,2038583,5135125,5135125,5379852,5379852,5135097,5135125,5135125,5379852,5379852,5135097,5135121,5135121,5067348,5067348,5067348,3554360,5135127,5135127,5135121,2018938,2018938,2018938,2018986,0,5135113,5135113,5135113)

    And abf.feecode in (50321, 50170)

    AND ap.voidflag is not null --= 'N'

    AND ap.paymentdate >= to_date ('01-OCT-2018')

GROUP BY fp.propertyrsn

Order by fp.propertyrsn
