### ISSUE TITLE
Create Issues - ROW Wish-list

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#191]
John to wave a magic wand and auto-create the issues on ROW's wish-list that don't already exist.

**Comment by TracyLinder** [comment]
[ROW IT Backlog.xlsx](https://github.com/cityofaustin/atd-amanda/files/4011227/ROW.IT.Backlog.xlsx)

**Comment by johnclary** [comment]
@TracyLinder 21 new issues created with the "Project: Row Wishlist" label. Happy new year! :)
