### ISSUE TITLE
Inspector Prioritization: How to handle missing "TOTAL_DAYS" ?

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#63]
Some permits do not have a TOTAL_DAYS value, and so we cannot weight their duration. How should we handle these @TracyLinder?

**Comment by TracyLinder** [comment]
Problem is only effecting DS permit types. Here is the section of the query that is calculating the total days for DS:
>trunc (trunc(f.expirydate) - trunc(f.issuedate)) as WZ_Duration

I'm looking into this.

**Comment by TracyLinder** [comment]
It's not working because there's no expiration date on these permits. These look like permits that were migrated from PIER. I'll ask Paloma to update them.
![image](https://user-images.githubusercontent.com/49930868/57867912-96942800-77c7-11e9-950b-2bf287229e3b.png)

**Comment by TracyLinder** [comment]
@johnclary This looks to be a one-off issue; I wouldn't expect it to happen again after Paloma's staff gets these few updated. I'm going to delete these from the current list, and I'll keep my eyes open for results with this error the next few pulls.
