### ISSUE TITLE
Inspector Dashboard: Road Class Challenges

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#69]
Working on the road classification scoring. Here's what we defined as a group:

Critical = 10
Arterial = 7
Collector = 5
Residential = 3

Street segments don't exactly match these categories. This is how I mapped the GIS road classfications:

Critical > Interstate, US and State Highways, Major Arterials

Arterial > Minor arterials

Collector > Collector

Residential > Local city/county, and everything else

I made a map to visualize this. The issue I see is that frontage roads are classified as local city/count roads, the same as a sleepy neighborhood streight. Gah:
https://arcg.is/0z4yS5

We can solve this, but it's a headache. One approach would be to flag any street with SVRD (service road) in the name, and classify that as an arterial. We may want to discuss as a group.

**Comment by johnclary** [comment]
@TracyLinder making sure you looked at this.

**Comment by TracyLinder** [comment]
@johnclary thanks, I hadn't seen this. The few we spot checked on Monday worked great. We can discuss at our next meeting.

**Comment by TracyLinder** [comment]
ROW project team are OK with the scoring described in the issue description.
