### ISSUE TITLE
Update Repo Readme and Directory Structure

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#7]
@TracyLinder would you update the readme for this repo so that it is more descriptive as well as follow the folder layout we discussed in this issue?
https://github.com/cityofaustin/atd-data-tech/issues/14

Realize I should have included you in this discussion. We can revisit if you like. Thanks.

**Comment by TracyLinder** [comment]
@johnclary thanks for the reminder. This is done; feedback is always welcome. :smiley_cat:

**Comment by johnclary** [comment]
@TracyLinder looks great. Protip: if you save your files with a `.sql` extension, github will show them with syntax highlighting. Just click the "edit" button to make that change to [this file](https://github.com/cityofaustin/atd-amanda/blob/master/plsql-queries/users-with-folder-permissions).
