### ISSUE TITLE
Inspector Prioritization Ph 1 Data Refresh

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#74]
Provide ROW w/ refreshed data by 6/20 10am

**Comment by TracyLinder** [comment]
@johnclary 
[Here](https://cityofaustin.sharepoint.com/sites/ATD/DTS/Shared%20Documents/Projects/Inspector%20Dashboard/duration_6.18.19.csv?d=w48f3c9e29a2745ac950ea3e9c9091ead) is the work zone duration.

[Here](https://cityofaustin.sharepoint.com/sites/ATD/DTS/Shared%20Documents/Projects/Inspector%20Dashboard/segments_6.18.19.csv?d=w7bdacb411fc24792afcd7c2f53c09d93) is the segment data.

**Comment by johnclary** [comment]
@TracyLinder scores attached. I could not get inspector areas added in time. Running into an issue with the spatial query that's going to take into next week.

[https://app.zenhub.com/files/183466621/116fde72-f79c-4e5a-add8-2a0d1a2f3e3e/download](https://app.zenhub.com/files/183466621/116fde72-f79c-4e5a-add8-2a0d1a2f3e3e/download)

**Comment by TracyLinder** [comment]
I created a folder for these on ROW's G drive and emailed the link to the team. 
>\\coacd.org\dfs\ATD\ATD\ROW Mgmt\ROW TTC Inspection Reports\Inspection Prioritization\2019
