### ISSUE TITLE
Inspector Prioritization Data Refresh 6/27

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#85]

**Comment by TracyLinder** [comment]
@johnclary the AMANDA data for this is [here](https://cityofaustin.sharepoint.com/sites/ATD/DTS/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FATD%2FDTS%2FShared%20Documents%2FProjects%2FInspector%20Dashboard&FolderCTID=0x012000A83D6DB7CCE68F4DB53FEE4A118F159A).

**Comment by johnclary** [comment]
Duplicate/closing
