### ISSUE TITLE
Inspector Prioritization Data Refresh 7/5

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#86]

**Comment by TracyLinder** [comment]
@johnclary 

WZ Duration is [here](https://cityofaustin.sharepoint.com/sites/ATD/DTS/Shared%20Documents/Projects/Inspector%20Dashboard/wz_duration_7.10.19.csv)
Segments are [here](https://cityofaustin.sharepoint.com/sites/ATD/DTS/Shared%20Documents/Projects/Inspector%20Dashboard/segments_7.10.19.csv)

**Comment by johnclary** [comment]
Data processed and sent to Mani this morning.

[permits_scored_11JUL2019.xlsx](https://github.com/cityofaustin/atd-amanda/files/3383152/permits_scored_11JUL2019.xlsx)
