### ISSUE TITLE
Get New Data for Week of June 24

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#88]

**Comment by johnclary** [comment]
Need new data to run the query this week.

I submitted a request to Mike D and Jenice M with a link to the inspector queries.

**Comment by johnclary** [comment]
Attached is the latest data. Need to merge tabs and tweak column headers before processing.

[https://app.zenhub.com/files/183466621/ea220d68-f0fd-4e27-8597-af0dd2fa5771/download](https://app.zenhub.com/files/183466621/ea220d68-f0fd-4e27-8597-af0dd2fa5771/download)

**Comment by TracyLinder** [comment]
Goodness, I really wish I had seen this before I did it tonight. ☹️

**Comment by johnclary** [comment]
test

**Comment by johnclary** [comment]
Done and sent to ROW team.
