### ISSUE TITLE
Meet Define ROW Open Datasets

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#89]
We need to define what the public ROW datasets will look like so that the inspector prioritization, BI, etc. can be automated.

**Permit Types for Open Data**

- DS
- EX
- RW
- UC
- LC

**Comment by johnclary** [comment]
@TracyLinder bumped to sprint 6. how's this coming?

**Comment by johnclary** [comment]
@TracyLinder bumped to sprint 12 ;)

**Comment by johnclary** [comment]
Scheduled for December 3rd.

**Comment by TracyLinder** [comment]
### ATD - AMANDA Open Data Conversation 

**Meeting Info**
John, Tracy, Surbhi reviewed on 12/4/19

**Primary (Master) ROW Data Set**
- We want one data set with everything (not published publicly)
- Verify it against portal (ask Surya) which fields are restricted from public view
- Identify which public views we want to create from the primary data set
- Eventually publish the primary for public viewing

**TDS Data**
- There is some data already published, but it doesn't include what we need to integrate the TDS KNACK app
- Create a new data set 
    - Worried about creating a duplicate data set
    - Make it a private data set to prevent duplication
- Get David (DSD) approval before moving forward
    - Tracy to send David an email 

**Next Steps:**
- Tracy move Inspector folder to google drive
- Tracy Email DSD (David)
- Tracy work on queries
- Tracy ping Surbhi when done, ask Sergio if more help w/ queries is needed
- Surbhi work on creating the open data set
- Reach out to CTM about automation

**Comment by TracyLinder** [comment]
[ROW Open Data.xlsx](https://github.com/cityofaustin/atd-amanda/files/3923472/ROW.Open.Data.xlsx)

**Comment by TracyLinder** [comment]
[Here](https://data.austintexas.gov/Building-and-Development/Site-Plan-Cases/mavg-96ck/data) is the site plan data set that Surbhi found.
